import React, { useState } from 'react';

const farmers = ['Grace Mensah', 'Ruth Tetteh', 'Isaac Boateng', 'John Farmer'];
const products = ['Input Finance Facility', 'Off-taker Secured Loan', 'Equipment Growth Facility'];

export default function BankLoanOperations({ onNotice }) {
  const [modal, setModal] = useState(null);
  const [loans, setLoans] = useState([]);
  const [product, setProduct] = useState({ name: '', type: '', rate: '', term: '', limit: '' });
  const [loan, setLoan] = useState({ borrower: farmers[0], product: products[0], amount: '', purpose: '', maturity: '' });
  const update = (setter) => (event) => setter((current) => ({ ...current, [event.target.name]: event.target.value }));
  const saveProduct = (event) => { event.preventDefault(); setModal(null); onNotice?.(`${product.name} product created.`); setProduct({ name: '', type: '', rate: '', term: '', limit: '' }); };
  const saveLoan = (event) => { event.preventDefault(); const id = `LN-${2050 + loans.length}`; setLoans((current) => [...current, { ...loan, id }]); setModal(null); onNotice?.(`${loan.borrower} loan ${id} sent to underwriting.`); setLoan({ borrower: farmers[0], product: products[0], amount: '', purpose: '', maturity: '' }); };
  return (
    <>
      <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
        <button type="button" onClick={() => setModal('loan')} className="rounded-xl border border-cyan-200 bg-cyan-50 p-5 text-left hover:border-cyan-400 hover:shadow-md"><span className="text-xs font-semibold uppercase tracking-wide text-cyan-700">Loan origination</span><h2 className="mt-2 text-lg font-bold text-slate-900">Add a new loan</h2><p className="mt-1 text-sm text-slate-600">Create a farmer facility and send it to underwriting.</p><span className="mt-4 inline-block rounded-lg bg-cyan-600 px-3 py-2 text-sm font-semibold text-white">Start loan</span></button>
        <button type="button" onClick={() => setModal('product')} className="rounded-xl border border-emerald-200 bg-emerald-50 p-5 text-left hover:border-emerald-400 hover:shadow-md"><span className="text-xs font-semibold uppercase tracking-wide text-emerald-700">Product management</span><h2 className="mt-2 text-lg font-bold text-slate-900">Add a loan product</h2><p className="mt-1 text-sm text-slate-600">Define the rate, term, limit, and product type.</p><span className="mt-4 inline-block rounded-lg bg-emerald-600 px-3 py-2 text-sm font-semibold text-white">Create product</span></button>
      </div>
      {loans.length > 0 && <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-semibold text-slate-900">Recently created loans</h2>{loans.map((item) => <div key={item.id} className="mt-2 flex justify-between rounded-lg bg-slate-50 p-3 text-sm"><span className="font-semibold">{item.id} · {item.borrower}</span><span>{item.amount} · Underwriting</span></div>)}</div>}
      {modal && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/60 p-4"><form onSubmit={modal === 'loan' ? saveLoan : saveProduct} className="w-full max-w-xl rounded-2xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><h2 className="text-2xl font-bold text-slate-900">{modal === 'loan' ? 'Add new loan' : 'Create loan product'}</h2><button type="button" onClick={() => setModal(null)} className="rounded-full bg-slate-100 px-3 py-1 text-sm font-semibold text-slate-600">Close</button></div>{modal === 'product' ? <div className="mt-5 grid grid-cols-1 gap-3 sm:grid-cols-2">{[['name', 'Product name'], ['type', 'Product type'], ['rate', 'Interest rate'], ['term', 'Repayment term'], ['limit', 'Facility limit']].map(([field, label]) => <label key={field} className="text-sm font-medium text-slate-700">{label}<input required name={field} value={product[field]} onChange={update(setProduct)} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2" /></label>)}</div> : <div className="mt-5 space-y-3"><label className="block text-sm font-medium text-slate-700">Borrower<select name="borrower" value={loan.borrower} onChange={update(setLoan)} className="mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-2">{farmers.map((item) => <option key={item}>{item}</option>)}</select></label><label className="block text-sm font-medium text-slate-700">Loan product<select name="product" value={loan.product} onChange={update(setLoan)} className="mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-2">{products.map((item) => <option key={item}>{item}</option>)}</select></label><div className="grid grid-cols-2 gap-3">{[['amount', 'Loan amount'], ['maturity', 'Maturity date']].map(([field, label]) => <label key={field} className="text-sm font-medium text-slate-700">{label}<input required name={field} value={loan[field]} onChange={update(setLoan)} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2" /></label>)}</div><label className="block text-sm font-medium text-slate-700">Purpose<input required name="purpose" value={loan.purpose} onChange={update(setLoan)} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2" /></label></div>}<div className="mt-6 flex justify-end gap-2"><button type="button" onClick={() => setModal(null)} className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold text-slate-700">Cancel</button><button type="submit" className="rounded-lg bg-cyan-600 px-4 py-2 text-sm font-semibold text-white">{modal === 'loan' ? 'Create loan' : 'Save product'}</button></div></form></div>}
    </>
  );
}
