import React, { useMemo, useState } from 'react';
import BankLoanOperations from './BankLoanOperations';

const pitches = [
  { farmer: 'Grace Mensah', crop: 'Rice', region: 'Tamale', ask: '$450,000', expected: '$620,000', score: 640, status: 'Ready for review', farmSize: '3.4 ha', yield: '19 tonnes', inputPlan: 'NPK fertilizer + certified seed', offTaker: 'Savanna Foods Ltd', coverage: '92%', climate: 'Low risk', repayment: '12 months' },
  { farmer: 'Ruth Tetteh', crop: 'Tomato', region: 'Ho', ask: '$600,000', expected: '$890,000', score: 715, status: 'Preferred', farmSize: '2.8 ha', yield: '19.9 tonnes', inputPlan: 'Solar irrigation + crop protection', offTaker: 'FreshRoute Markets', coverage: '78%', climate: 'Low risk', repayment: '9 months' },
  { farmer: 'Isaac Boateng', crop: 'Cassava', region: 'Cape Coast', ask: '$320,000', expected: '$510,000', score: 610, status: 'Needs documents', farmSize: '5.1 ha', yield: '19.4 tonnes', inputPlan: 'Certified seed + transport', offTaker: 'Golden Harvest Co.', coverage: '64%', climate: 'Moderate risk', repayment: '12 months' },
];

const loanRequests = [
  { id: 'LR-2048', borrower: 'Grace Mensah', purpose: 'Rice inputs and irrigation', amount: '$450,000', coverage: '92%', stage: 'Underwriting', risk: 'Low' },
  { id: 'LR-2047', borrower: 'Isaac Boateng', purpose: 'Certified seed and transport', amount: '$320,000', coverage: '64%', stage: 'Documents requested', risk: 'Medium' },
  { id: 'LR-2042', borrower: 'John Farmer', purpose: 'Mechanization service', amount: '$200,000', coverage: '64%', stage: 'Risk review', risk: 'Watch' },
];

const products = [
  { name: 'Input Finance Facility', type: 'Seasonal credit', rate: '8.5%', term: '12 months', limit: '$500K', status: 'Active' },
  { name: 'Off-taker Secured Loan', type: 'Purchase-backed', rate: '7.8%', term: '9 months', limit: '$1.2M', status: 'Active' },
  { name: 'Equipment Growth Facility', type: 'Asset finance', rate: '10.2%', term: '24 months', limit: '$750K', status: 'Draft' },
];

const portfolio = [
  ['Rice', '$684K', '42 farms', '4.1%'],
  ['Maize', '$492K', '38 farms', '5.8%'],
  ['Tomato', '$371K', '24 farms', '3.2%'],
  ['Cassava', '$253K', '19 farms', '6.4%'],
];

const investors = [
  ['AgriGrowth Fund', '$2.4M capacity', 'Impact fund', 'Active'],
  ['Northern Development Bank', '$1.8M capacity', 'Institutional', 'Active'],
  ['Harvest Capital Partners', '$950K capacity', 'Private capital', 'Review'],
];

const financialDirectory = [
  ['AgriFinance Bank', 'Bank', 'Farm loans · Equipment finance', '8-12%'],
  ['Rural Microfinance', 'Microfinance', 'Group lending · Savings', '14-18%'],
  ['AgriShield Insurance', 'Insurance', 'Crop · Weather index cover', 'Risk based'],
];

const BankSafeVestDashboard = ({ onNotice }) => {
  const [activeTab, setActiveTab] = useState('overview');
  const [selectedRequest, setSelectedRequest] = useState(null);
  const [selectedPitch, setSelectedPitch] = useState(null);
  const [productStatus, setProductStatus] = useState({});
  const [pitchFilter, setPitchFilter] = useState('All');
  const [showProductForm, setShowProductForm] = useState(false);
  const [showLoanForm, setShowLoanForm] = useState(false);
  const [customProducts, setCustomProducts] = useState([]);
  const [newProduct, setNewProduct] = useState({ name: '', type: 'Seasonal credit', rate: '', term: '', limit: '' });
  const [newLoan, setNewLoan] = useState({ borrower: 'Grace Mensah', product: 'Input Finance Facility', amount: '', purpose: '', maturity: '' });
  const [createdLoans, setCreatedLoans] = useState([]);

  const filteredPitches = useMemo(() => pitches.filter((pitch) => pitch.status === pitchFilter || pitchFilter === 'All'), [pitchFilter]);
  const tabs = [
    ['overview', 'Overview'], ['pitches', 'Farm pitches'], ['requests', 'Loan requests'], ['products', 'Loan products'],
    ['portfolio', 'Portfolio'], ['crowdfunding', 'Crowdfunding'], ['investors', 'Investor directory'], ['financial', 'Financial directory'],
  ];

  const notify = (message) => onNotice?.(message);

  return (
    <div className="space-y-6">
      <BankLoanOperations onNotice={notify} />
      <section className="relative overflow-hidden rounded-xl border border-slate-800 bg-slate-900 p-6 text-white shadow-sm">
        <div className="pointer-events-none absolute -right-16 -top-20 h-56 w-56 rounded-full border-[28px] border-cyan-400/10" />
        <div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-cyan-300">SafeVest | Bank workspace</p><h1 className="mt-2 text-3xl font-bold">Agricultural finance command center</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-300">Evaluate farm opportunities, publish lending products, manage requests, and monitor the performance of your agricultural credit portfolio.</p></div><span className="rounded-full border border-emerald-500/40 bg-emerald-500/10 px-3 py-1 text-xs font-semibold text-emerald-300">Bank operations live</span></div>
        <div className="mt-6 grid grid-cols-2 gap-3 lg:grid-cols-5">{[['Capital deployed', '$1.8M', '+12.8% cycle'], ['Active facilities', '123', '96% performing'], ['Pending requests', '18', '6 need review'], ['Portfolio at risk', '4.6%', '-0.8% month'], ['Crowdfunding pool', '$420K', '8 campaigns']].map(([label, value, detail]) => <div key={label} className="rounded-lg border border-slate-700 bg-slate-800 p-3"><p className="text-xs text-slate-400">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p><p className="mt-1 text-xs text-cyan-300">{detail}</p></div>)}</div>
      </section>

      <div className="flex gap-2 overflow-x-auto border-b border-slate-200 pb-3">{tabs.map(([id, label]) => <button key={id} type="button" onClick={() => setActiveTab(id)} className={`whitespace-nowrap rounded-lg px-3 py-2 text-sm font-semibold ${activeTab === id ? 'bg-cyan-600 text-white' : 'bg-slate-100 text-slate-600 hover:bg-slate-200'}`}>{label}</button>)}</div>

      {activeTab === 'overview' && <div className="grid grid-cols-1 gap-6 xl:grid-cols-[1.3fr_1fr]"><div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold text-slate-900">Lending pipeline</h2><p className="text-sm text-slate-500">Current flow from pitch to active loan</p></div><span className="text-xs font-semibold text-emerald-700">18 open actions</span></div><div className="mt-5 space-y-4">{[['New farm pitches', '12', 'Profiled and awaiting screening', 'bg-sky-500'], ['Credit assessment', '8', 'Fame Base and climate review', 'bg-cyan-500'], ['Underwriting', '6', 'Loan officer decision required', 'bg-amber-500'], ['Active facilities', '123', 'Monitoring repayments and production', 'bg-emerald-500']].map(([label, value, detail, tone]) => <div key={label} className="flex items-center gap-3"><div className={`h-10 w-10 rounded-lg ${tone}`} /><div className="flex-1"><div className="flex justify-between text-sm"><span className="font-semibold text-slate-800">{label}</span><span className="font-bold text-slate-900">{value}</span></div><p className="text-xs text-slate-500">{detail}</p><div className="mt-2 h-2 rounded-full bg-slate-100"><div className={`h-full rounded-full ${tone}`} style={{ width: `${Math.min(Number(value) / 123 * 100 + 12, 100)}%` }} /></div></div></div>)}</div></div><div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-semibold text-slate-900">Bank action queue</h2><p className="text-sm text-slate-500">Prioritized work across SafeVest</p><div className="mt-4 space-y-3">{['Review 6 loan requests in underwriting', 'Publish the Equipment Growth Facility', 'Confirm investor allocation for rice portfolio', 'Reconcile 2 settlement variances'].map((item, index) => <button key={item} type="button" onClick={() => notify(`${item} opened.`)} className="flex w-full items-start gap-3 rounded-lg border border-slate-200 p-3 text-left hover:bg-slate-50"><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-cyan-100 text-xs font-bold text-cyan-700">{index + 1}</span><span className="text-sm text-slate-700">{item}</span></button>)}</div></div></div>}

      {activeTab === 'pitches' && <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><h2 className="text-lg font-semibold text-slate-900">Farm pitches for bank review</h2><p className="text-sm text-slate-500">Assess productive opportunities before creating a facility</p></div><select value={pitchFilter} onChange={(event) => setPitchFilter(event.target.value)} className="rounded-lg border border-slate-300 px-3 py-2 text-sm"><option>All</option><option>Ready for review</option><option>Preferred</option><option>Needs documents</option></select></div><div className="mt-5 grid grid-cols-1 gap-4 md:grid-cols-3">{filteredPitches.map((pitch) => <div key={pitch.farmer} className="rounded-xl border border-slate-200 p-4"><div className="flex items-start justify-between"><div><span className="text-xs font-semibold uppercase tracking-wide text-cyan-600">{pitch.crop} · {pitch.region}</span><h3 className="mt-1 font-semibold text-slate-900">{pitch.farmer}</h3></div><span className="rounded-full bg-emerald-50 px-2 py-1 text-xs font-semibold text-emerald-700">{pitch.status}</span></div><div className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><p className="text-xs text-slate-500">Requested</p><p className="font-bold text-slate-800">{pitch.ask}</p></div><div><p className="text-xs text-slate-500">Expected return</p><p className="font-bold text-emerald-700">{pitch.expected}</p></div><div><p className="text-xs text-slate-500">Fame score</p><p className="font-bold text-slate-800">{pitch.score}</p></div><div><p className="text-xs text-slate-500">Coverage</p><p className="font-bold text-cyan-700">{pitch.coverage}</p></div></div><button type="button" onClick={() => setSelectedPitch(pitch)} className="mt-4 w-full rounded-lg bg-cyan-600 px-3 py-2 text-sm font-semibold text-white hover:bg-cyan-700">Open pitch details</button></div>)}</div></div>}

      {activeTab === 'requests' && <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div><h2 className="text-lg font-semibold text-slate-900">Loan requests</h2><p className="text-sm text-slate-500">Receive, screen, approve, and manage farmer facilities</p></div><div className="mt-5 overflow-x-auto"><table className="min-w-[850px] w-full text-left text-sm"><thead className="border-b border-slate-200 text-xs uppercase tracking-wide text-slate-500"><tr>{['Request', 'Borrower', 'Purpose', 'Amount', 'Coverage', 'Stage', 'Risk', 'Action'].map((heading) => <th key={heading} className="px-3 py-3">{heading}</th>)}</tr></thead><tbody>{loanRequests.map((request) => <tr key={request.id} className="border-b border-slate-100"><td className="px-3 py-4 font-semibold text-slate-700">{request.id}</td><td className="px-3 py-4">{request.borrower}</td><td className="px-3 py-4 text-slate-500">{request.purpose}</td><td className="px-3 py-4 font-semibold">{request.amount}</td><td className="px-3 py-4 text-emerald-700">{request.coverage}</td><td className="px-3 py-4"><span className="rounded-full bg-slate-100 px-2 py-1 text-xs">{request.stage}</span></td><td className="px-3 py-4"><span className="font-semibold text-amber-700">{request.risk}</span></td><td className="px-3 py-4"><button type="button" onClick={() => setSelectedRequest(request)} className="font-semibold text-cyan-700 hover:underline">Manage</button></td></tr>)}</tbody></table></div></div>}

      {activeTab === 'products' && <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold text-slate-900">Loan products</h2><p className="text-sm text-slate-500">Publish products for productive agricultural finance</p></div><button type="button" onClick={() => notify('New loan product form opened.')} className="rounded-lg bg-cyan-600 px-4 py-2 text-sm font-semibold text-white">Add product</button></div><div className="mt-5 grid grid-cols-1 gap-4 md:grid-cols-3">{products.map((product) => <div key={product.name} className="rounded-xl border border-slate-200 p-4"><div className="flex justify-between"><div><span className="text-xs font-semibold uppercase tracking-wide text-cyan-600">{product.type}</span><h3 className="mt-1 font-semibold text-slate-900">{product.name}</h3></div><span className={`rounded-full px-2 py-1 text-xs font-semibold ${product.status === 'Active' ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-700'}`}>{product.status}</span></div><div className="mt-4 grid grid-cols-3 gap-2 text-xs"><span><strong className="block text-slate-800">{product.rate}</strong><small className="text-slate-400">Rate</small></span><span><strong className="block text-slate-800">{product.term}</strong><small className="text-slate-400">Term</small></span><span><strong className="block text-slate-800">{product.limit}</strong><small className="text-slate-400">Limit</small></span></div><button type="button" onClick={() => { setProductStatus((previous) => ({ ...previous, [product.name]: 'Updated' })); notify(`${product.name} product updated.`); }} className="mt-4 w-full rounded-lg border border-cyan-300 px-3 py-2 text-sm font-semibold text-cyan-700">{productStatus[product.name] || 'Manage product'}</button></div>)}</div></div>}

      {activeTab === 'portfolio' && <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-semibold text-slate-900">Loan portfolio</h2><p className="text-sm text-slate-500">Exposure and repayment performance by crop</p><div className="mt-5 grid grid-cols-1 gap-3 md:grid-cols-2">{portfolio.map(([crop, amount, farms, risk]) => <div key={crop} className="rounded-lg border border-slate-200 p-4"><div className="flex justify-between"><span className="font-semibold text-slate-800">{crop}</span><span className="text-sm font-bold text-slate-900">{amount}</span></div><div className="mt-3 h-2 rounded-full bg-slate-100"><div className="h-full rounded-full bg-cyan-500" style={{ width: `${parseInt(amount.replace(/[$K]/g, ''), 10) / 7}%` }} /></div><div className="mt-2 flex justify-between text-xs text-slate-500"><span>{farms}</span><span>At risk: {risk}</span></div></div>)}</div><div className="mt-5 rounded-lg bg-slate-900 p-4 text-white"><div className="flex justify-between text-sm text-slate-300"><span>Total portfolio</span><span>96% performing</span></div><p className="mt-1 text-3xl font-bold">$1.8M</p></div></div>}

      {activeTab === 'crowdfunding' && <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-semibold text-slate-900">Crowdfunding oversight</h2><p className="text-sm text-slate-500">Monitor campaigns connected to bank-managed farm opportunities</p><div className="mt-5 grid grid-cols-1 gap-4 md:grid-cols-3">{[['Northern Rice Expansion', '$148K raised', '74% funded'], ['Women Tomato Growers', '$96K raised', '62% funded'], ['Solar Irrigation Cluster', '$72K raised', '48% funded']].map(([name, raised, funded]) => <div key={name} className="rounded-lg border border-slate-200 p-4"><span className="text-xs font-semibold text-cyan-600">Campaign</span><h3 className="mt-1 font-semibold text-slate-900">{name}</h3><p className="mt-3 text-lg font-bold text-slate-800">{raised}</p><p className="text-sm text-emerald-700">{funded}</p><button type="button" onClick={() => notify(`${name} campaign opened.`)} className="mt-4 w-full rounded-lg border border-cyan-300 px-3 py-2 text-sm font-semibold text-cyan-700">View campaign</button></div>)}</div></div>}

      {activeTab === 'investors' && <DirectoryTable title="Investor directory" description="Capital partners available for co-financing and syndication" rows={investors} headers={['Investor', 'Capacity', 'Type', 'Status']} />}
      {activeTab === 'financial' && <DirectoryTable title="Financial directory" description="Partner institutions for referrals, insurance, and risk support" rows={financialDirectory} headers={['Institution', 'Type', 'Services', 'Terms']} />}

      {selectedPitch && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/60 p-4" role="dialog" aria-modal="true" aria-labelledby="pitch-title"><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-cyan-600">Farm pitch for underwriting</p><h2 id="pitch-title" className="mt-1 text-2xl font-bold text-slate-900">{selectedPitch.farmer}</h2><p className="text-sm text-slate-500">{selectedPitch.crop} · {selectedPitch.region} · {selectedPitch.status}</p></div><button type="button" onClick={() => setSelectedPitch(null)} className="rounded-full bg-slate-100 px-3 py-1.5 text-sm font-semibold text-slate-600 hover:bg-slate-200">Close</button></div><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4">{[['Requested', selectedPitch.ask], ['Expected return', selectedPitch.expected], ['Fame score', selectedPitch.score], ['Farm size', selectedPitch.farmSize], ['Yield forecast', selectedPitch.yield], ['Off-taker cover', selectedPitch.coverage], ['Climate risk', selectedPitch.climate], ['Repayment', selectedPitch.repayment]].map(([label, value]) => <div key={label} className="rounded-lg bg-slate-50 p-3"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-sm font-semibold text-slate-800">{value}</p></div>)}</div><div className="mt-5 grid grid-cols-1 gap-3 sm:grid-cols-2"><div className="rounded-xl border border-cyan-200 bg-cyan-50 p-4"><p className="text-xs font-semibold uppercase tracking-wide text-cyan-700">Input plan</p><p className="mt-2 text-sm font-semibold text-slate-800">{selectedPitch.inputPlan}</p><p className="mt-2 text-xs text-slate-600">Finance is released against verified delivery and production milestones.</p></div><div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4"><p className="text-xs font-semibold uppercase tracking-wide text-emerald-700">Bank recommendation</p><p className="mt-2 text-sm font-semibold text-slate-800">{selectedPitch.score >= 640 && selectedPitch.coverage !== '64%' ? 'Proceed to conditional approval' : 'Request documents before approval'}</p><p className="mt-2 text-xs text-slate-600">Review land records, off-taker commitment, and climate exposure before disbursement.</p></div></div><div className="mt-6 flex flex-wrap justify-end gap-2"><button type="button" onClick={() => { setSelectedPitch(null); setActiveTab('requests'); }} className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50">View loan requests</button><button type="button" onClick={() => { setSelectedPitch(null); notify(`${selectedPitch.farmer} pitch sent to underwriting.`); }} className="rounded-lg bg-cyan-600 px-4 py-2 text-sm font-semibold text-white hover:bg-cyan-700">Send to underwriting</button></div></div></div>}

      {selectedRequest && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/60 p-4" role="dialog" aria-modal="true" aria-labelledby="loan-request-title"><div className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-wide text-cyan-600">Loan request</p><h2 id="loan-request-title" className="mt-1 text-2xl font-bold text-slate-900">{selectedRequest.id}</h2></div><button type="button" onClick={() => setSelectedRequest(null)} className="rounded-full bg-slate-100 px-3 py-1 text-sm font-semibold text-slate-600">Close</button></div><div className="mt-5 grid grid-cols-2 gap-3">{[['Borrower', selectedRequest.borrower], ['Purpose', selectedRequest.purpose], ['Amount', selectedRequest.amount], ['Off-taker cover', selectedRequest.coverage], ['Stage', selectedRequest.stage], ['Risk', selectedRequest.risk]].map(([label, value]) => <div key={label} className="rounded-lg bg-slate-50 p-3"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-sm font-semibold text-slate-800">{value}</p></div>)}</div><div className="mt-5 flex gap-2"><button type="button" onClick={() => { setSelectedRequest(null); notify(`${selectedRequest.id} approved for disbursement.`); }} className="flex-1 rounded-lg bg-emerald-600 px-3 py-2 text-sm font-semibold text-white">Approve</button><button type="button" onClick={() => { setSelectedRequest(null); notify(`Documents requested for ${selectedRequest.id}.`); }} className="flex-1 rounded-lg bg-amber-500 px-3 py-2 text-sm font-semibold text-white">Request documents</button></div></div></div>}
    </div>
  );
};

const DirectoryTable = ({ title, description, rows, headers }) => <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-semibold text-slate-900">{title}</h2><p className="text-sm text-slate-500">{description}</p><div className="mt-5 overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="border-b border-slate-200 text-xs uppercase tracking-wide text-slate-500"><tr>{headers.map((header) => <th key={header} className="px-3 py-3">{header}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row[0]} className="border-b border-slate-100"><td className="px-3 py-3 font-semibold text-slate-800">{row[0]}</td>{row.slice(1).map((cell, index) => <td key={`${row[0]}-${index}`} className="px-3 py-3 text-slate-600">{cell}</td>)}</tr>)}</tbody></table></div></div>;

export default BankSafeVestDashboard;
